---
name: Setup Node.js
description: Setup Node.js internal action
inputs:
  pnpm-version:
    description: 'Version of pnpm to use. Default is 10.'
    required: false
    default: '10'
  node-version:
    description: 'Version of Node.js to use. Default is 24.'
    required: false
    default: '24'
  use-github-npm-registry:
    description: |-
      Whether to use GitHub npm registry. Default is false. This will require `NODE_AUTH_TOKEN` secret to be set as an
      environment variable.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v5
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Use Node.js
      uses: actions/setup-node@v6.3.0
      if: ${{ inputs.use-github-npm-registry }}
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://npm.pkg.github.com/
        cache: 'pnpm'

    - name: Use Node.js
      uses: actions/setup-node@v6.3.0
      if: ${{ !inputs.use-github-npm-registry }}
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
